### ISSUE TITLE
Removing mix.lock from maru_reload breaks build

### ISSUE THREAD

**Issue by msuess** [falood/maru_examples#3]
Steps to reproduce:

1. clone the repo
2. `cd maru_reload`
3. `rm mix.lock`
4. `mix deps.get`
5. `iex -S mix`

Result:
```
** (Mix) Could not start application exfswatch: exited in: ExFSWatch.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function :fsevents.find_executable/0 is undefined (module :fsevents is not available)
            :fsevents.find_executable()
            (exfswatch) lib/exfswatch.ex:19: ExFSWatch.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

Disclaimer: I'm an Elixir noob so I might be doing something wrong here.

**Comment by falood** [comment]
I'm sorry that's a bug of exfswatch.
I'm trying to fix it and build a new version.
You can add such line to your `deps` to fix it temporary `{:fs, github: "synrc/fs", override: true}`
